# name: Deploy to Production

# on:
#   push:
#     branches:
#       - main

# concurrency:
#   group: ${{ github.workflow }}-${{ github.ref }}
#   cancel-in-progress: false

# jobs:
#   Deploy:
#     if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
#     runs-on: ubuntu-latest

#     env:
#       DOCKER_BUILDKIT: 1
#       RAILS_ENV: production
#       RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
#       KAMAL_REGISTRY_PASSWORD: ${{ secrets.KAMAL_REGISTRY_PASSWORD }} # this is the password for the Docker registry
#       KAMAL_REGISTRY_USERNAME: ${{ secrets.KAMAL_REGISTRY_USERNAME }} # this is the username for the Docker registry
#       DATABASE_URL: ${{ secrets.DATABASE_URL }}
#       APPSIGNAL_PUSH_API_KEY: ${{ secrets.APPSIGNAL_PUSH_API_KEY }}
#       APP_REVISION: ${{ github.sha }}

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Set up Ruby
#         uses: ruby/setup-ruby@v1
#         with:
#           ruby-version: .ruby-version # This will use the version from .ruby-version
#           bundler-cache: true

#       - name: Install dependencies
#         run: |
#           gem install kamal

#       - uses: webfactory/ssh-agent@v0.9.1
#         with:
#           ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

#       - name: Set up Docker Buildx
#         id: buildx
#         uses: docker/setup-buildx-action@v3
    
#       - name: Run deploy command
#         run: kamal deploy
